name: example-push

trigger:
  events: ["push"]
  branches: ["feature-*"]

tasks:
  hello:
    steps:
      - image: alpine
        script: |
          #!/usr/bin/env sh

          echo "HELLO UNDERTABLE"
