apiVersion: commons.cloudx.io/v1alpha1
kind: ProviderConfig
metadata:
  name: app-1-provider-config-dev
spec:
  type: AWS
  source: STATIC_CREDENTIALS
  secretRef:
    name: aws-dev-creds
    namespace: default
  awsConfig:
    region: 'us-east-1'
